@startmindmap
* ระบบทัวร์
** หน้าแสดงผล
*** แสดงรายการทัว
**** สถานะทัวร์
**** จำนวนสมาชิกในทัวร์
**** จำนวนสถานะทัวร์
*** แสดงข้อมูลทัวร์
**** รายละเอียดทัวร์
**** รายละเอียดโรงแรม
**** รายละเอียดไกด์
**** รายละเอียดพาหนะ
**** รายละเอียดลูกทัวร์
** ระบบจัดการทัวร์
*** เพิ่มข้อมูลทัวร์
**** ข้อมูลทัวร์
**** ข้อมูลไกด์
***** ค้นหา
***** เพิ่มลงทัวร์
***** เพิ่มลงระบบ
**** ข้อมูลโรงแรม
***** ค้นหา
***** เพิ่มลงทัวร์
***** เพิ่มลงระบบ
**** ข้อมูลพาหนะ
***** ค้นหา
***** เพิ่มลงทัวร์
***** เพิ่มลงระบบ
**** ข้อมูลลูกทัวร์
***** ค้นหา
***** เพิ่มลงทัวร์
***** เพิ่มลงระบบ
***** แจ้งเตือน Passport หมดอายุ
***** แจ้งเตือน วันเกิดสมาชิก
*** จัดการข้อมูลทัวร์
**** ข้อมูลทัวร์
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลไกด์
***** เพิ่ม
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลโรงแรม
***** เพิ่ม
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลยานพาหนะ
***** เพิ่ม
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลลูกทัวร์
***** เพิ่ม
***** แก้ไขข้อมูล
***** ลบข้อมูล
*** จัดการใบต่าง ๆ
**** จัดการใบเสนอราคา
***** สร้างใบเสนอราคา
***** แก้ไขใบเสนอราคา
***** ลบใบเสนอราคา
**** จัดการใบวางบิล
***** สร้างใบวางบิล
***** แก้ไขใบวางบิล
***** ลบใบวางบิล
**** สร้างใบแท็กติดกระเป๋า
*** คอมเมนต์
**** คอมเมนต์ทัวร์
***** เพิ่ม
***** แก้ไข
***** ลบ
**** คอมเมนต์ไกด์
***** เพิ่ม
***** แก้ไข
***** ลบ
**** คอมเมนต์โรงแรม
***** เพิ่ม
***** แก้ไข
***** ลบ
**** คอมเมนต์สมาชิก
***** เพิ่ม
***** แก้ไข
***** ลบ
**** คอมเมนต์ยานพาหนะ
***** เพิ่ม
***** แก้ไข
***** ลบ
' ** จัดการข้อมูลบริษัทย์
' *** ข้อมูลพนักงาน
' *** จัดการข้อมูลเกี่ยวกับทัวร์
' **** ข้อมูลสมาชิกทัวร์
' **** ข้อมูลโรงแรม
' **** ข้อมูลพาหนะ
** การจัดการ
*** จัดการข้อมูลในระบบ
**** ข้อมูลพนักงาน
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
**** ข้อมูลไกด์
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
**** ข้อมูลโรงแรม
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
**** ข้อมูลพาหนะ
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
**** ข้อมูลลูกทัวร์
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
*** รายงานรายรับรายจ่าย
**** แบบรายวัน
**** แบบรายรายเดือน
**** แบบรายปี
**** แบบรายเดือนแบบวัน
@endmindmap