@startmindmap
* Back Office

** ระบบ Login

** ระบบจัดการทัวร์
*** สร้างทัวร์
**** เพิ่มข้อมูล
**** ข้อมูลไกด์
***** ค้นหา
***** เพิ่มไกด์
***** สร้างไกด์ใหม่
**** ข้อมูลโรงแรม
***** ค้นหา
***** เพิ่มโรงแรม
***** สร้างโรงแรมใหม่
**** ข้อมูลพาหนะ
***** ค้นหา
***** เพิ่มพาหนะ
***** สร้างพาหนะใหม่
**** ข้อมูลลูกทัวร์
***** ค้นหา
***** เพิ่มลูกทัวร์
****** แจ้งเตือน Passport หมดอายุ
****** แจ้งเตือน วันเกิดสมาชิก
****** แจ้งเตือน หมายเหตุสมาชิก
***** สร้างลูกทัวร์ใหม่
*** จัดการข้อมูลทัวร์
**** ข้อมูลทัวร์
***** แก้ไขข้อมูล
**** ข้อมูลไกด์
***** เพิ่มไกด์
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลโรงแรม
***** เพิ่มโรงแรม
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลยานพาหนะ
***** เพิ่มยานพาหนะ
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลลูกทัวร์
***** เพิ่มลูกทัวร์
****** แจ้งเตือน
******* แจ้งเตือน Passport หมดอายุ
******* แจ้งเตือน วันเกิดสมาชิก
******* แจ้งเตือน หมายเหตุสมาชิก
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ลบทัวร์
*** จัดการเอกสารต่าง ๆ
**** จัดการใบเสนอราคา
***** สร้างใบเสนอราคา
***** แก้ไขใบเสนอราคา
***** ลบใบเสนอราคา
***** Export PDF and Print
***** จัดการใบวางบิล
****** สร้างใบวางบิล
****** แก้ไขใบวางบิล
****** ลบใบวางบิล
****** Export PDF and Print
**** สร้างใบกำกับภาษี
***** Export PDF and Print
***** สร้างใบเสร็จ
****** Export PDF and Print
**** สร้างใบสำคัญรับเงิน
***** Export PDF and Print
**** สร้างใบสั่งงานมัคคุเทศก์
***** Export PDF and Print
**** ใบแท็กติดกระเป๋า Export PDF and Print
*** คอมเมนต์
**** คอมเมนต์ทัวร์
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
**** คอมเมนต์ไกด์
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
**** คอมเมนต์โรงแรม
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
**** คอมเมนต์สมาชิก
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
**** คอมเมนต์ยานพาหนะ
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
*** แจ้งเตือน
**** แจ้งเตือน Passport ลูกทัวร์หมดอายุ (ไม่มั่นใจ*)
*** Export ข้อมูลทัวร์เป็น PDF และ Print
*** สถานะทัวร์
**** กำลังรอ
**** พร้อม
**** จบทริป

** จัดการข้อมูลในระบบ
*** ข้อมูลพนักงาน
**** ค้นหา
**** เพิ่ม
**** แก้ไข
**** ลบ
**** ระดับพนักงาน
*** ข้อมูลไกด์
**** ค้นหา
**** เพิ่ม
**** แก้ไข
**** ลบ
**** คอมเมนต์
***** เพิ่ม
***** แก้ไข
***** ลบ
*** ข้อมูลโรงแรม
**** ค้นหา
**** เพิ่ม
**** แก้ไข
**** ลบ
**** คอมเมนต์
***** เพิ่ม
***** แก้ไข
***** ลบ
*** ข้อมูลพาหนะ
**** ค้นหา
**** เพิ่ม
**** แก้ไข
**** ลบ
**** คอมเมนต์
***** เพิ่ม
***** แก้ไข
***** ลบ
*** ข้อมูลลูกทัวร์
**** ค้นหา
**** เพิ่ม
**** แก้ไข
**** ลบ
**** คอมเมนต์
***** เพิ่ม
***** แก้ไข
***** ลบ

** การเงินของบริษัท
*** สร้างใบเบิกค่าใช้จ่าย
**** ใบเบิกเงินสดย่อย
***** แก้ไขใบเบิกเงินสดย่อย
***** ลบใบเบิกเงินสดย่อย
***** Print and export to PDF
***** ออกใบเคลียร์
****** ใบเคลียร์เงินสด
******* แก้ไขใบเคลียร์เงินสด
******* ลบใบเคลียร์เงินสด
******* Print and export to PDF

** รายงานรายรับรายจ่าย
*** ค้นหา
*** แสดงแบบรายวัน
*** แสดงแบบรายรายเดือน
*** แสดงแบบรายปี
*** แสดงแบบรายเดือนแบบวัน
*** Export to Excel
@endmindmap