' รวม
@startmindmap
* ระบบทัวร์
** หน้าแสดงผล
*** แสดงรายการทัว
**** ค้นหาทัวร์
**** สถานะทัวร์
**** จำนวนสมาชิกในทัวร์
**** จำนวนสถานะทัวร์
**** สถานะทัวร์
*** แสดงข้อมูลทัวร์
**** รายละเอียดทัวร์
**** รายละเอียดโรงแรม
**** รายละเอียดไกด์

**** รายละเอียดพาหนะ
**** รายละเอียดลูกทัวร์
** ระบบจัดการทัวร์
*** เพิ่มข้อมูลทัวร์
**** ข้อมูลทัวร์
***** เพิ่มข้อมูล
**** ข้อมูลไกด์
***** ค้นหา
***** เพิ่มไกด์
***** สร้างไกด์ใหม่
**** ข้อมูลโรงแรม
***** ค้นหา
***** เพิ่มโรงแรม
***** สร้างโรงแรมใหม่
**** ข้อมูลพาหนะ
***** ค้นหา
***** เพิ่มพาหนะ
***** สร้างพาหนะใหม่
**** ข้อมูลลูกทัวร์
***** ค้นหา
***** เพิ่มลูกทัวร์
***** สร้างลูกทัวร์ใหม่
***** แจ้งเตือน Passport หมดอายุ
***** แจ้งเตือน วันเกิดสมาชิก
***** แจ้งเตือน หมายเหตุสมาชิก
*** จัดการข้อมูลทัวร์
**** ข้อมูลทัวร์
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลไกด์
***** เพิ่มไกด์
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลโรงแรม
***** เพิ่มโรงแรม
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลยานพาหนะ
***** เพิ่มยานพาหนะ
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลลูกทัวร์
***** เพิ่มลูกทัวร์
***** แก้ไขข้อมูล
***** ลบข้อมูล
***** แจ้งเตือน Passport หมดอายุ
***** แจ้งเตือน วันเกิดสมาชิก
***** แจ้งเตือน หมายเหตุสมาชิก
*** จัดการเอกสารต่าง ๆ
**** จัดการใบเสนอราคา
***** สร้างใบเสนอราคา
***** แก้ไขใบเสนอราคา
***** ลบใบเสนอราคา
***** Export PDF and Print
***** จัดการใบวางบิล
****** สร้างใบวางบิล
****** แก้ไขใบวางบิล
****** ลบใบวางบิล
****** Export PDF and Print
**** สร้างใบกำกับภาษี
***** Export PDF and Print
***** สร้างใบเสร็จ
****** Export PDF and Print
**** สร้างใบสำคัญรับเงิน
***** Export PDF and Print
**** สร้างใบสั่งงานมัคคุเทศก์
***** Export PDF and Print
**** ใบแท็กติดกระเป๋า Export PDF and Print
*** คอมเมนต์
**** คอมเมนต์ทัวร์
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
**** คอมเมนต์ไกด์
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
**** คอมเมนต์โรงแรม
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
**** คอมเมนต์สมาชิก
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
**** คอมเมนต์ยานพาหนะ
***** เพิ่ม
***** แก้ไข
***** ลบ
***** เลือกวันเวลา
*** แจ้งเตือน
**** แจ้งเตือน Passport ลูกทัวร์หมดอายุ
*** Export ข้อมูลทัวร์เป็น PDF และ Print
** การจัดการ
*** จัดการข้อมูลในระบบ
**** ข้อมูลพนักงาน
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** ระดับพนักงาน
**** ข้อมูลไกด์
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
**** ข้อมูลโรงแรม
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
**** ข้อมูลพาหนะ
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
**** ข้อมูลลูกทัวร์
***** ค้นหา
***** เพิ่ม
***** แก้ไข
***** ลบ
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
*** การเงิน
**** จัดการใบเบิกค่าใช้จ่าย
***** สร้างใบเบิกค่าใช้จ่าย
****** ใบเคลียร์
******* ข้อมูลใบเคลียร์
******* สร้างใบเคลียร์
*** รายงานรายรับรายจ่าย
**** ค้นหา
**** แสดงแบบรายวัน
**** แสดงแบบรายรายเดือน
**** แสดงแบบรายปี
**** แสดงแบบรายเดือนแบบวัน
**** Export to Excel
@endmindmap

' อบ
@startmindmap
* ระบบทัวร์
** หน้าแสดงผล
*** แสดงรายการทัว
**** ค้นหาทัวร์
**** สถานะทัวร์
**** จำนวนสมาชิกในทัวร์
**** จำนวนสถานะทัวร์
**** สถานะทัวร์
*** แสดงข้อมูลทัวร์
**** รายละเอียดทัวร์
**** รายละเอียดโรงแรม
**** รายละเอียดไกด์
**** รายละเอียดพาหนะ
**** รายละเอียดลูกทัวร์
** ระบบจัดการทัวร์
*** เพิ่มข้อมูลทัวร์
**** ข้อมูลทัวร์
***** เพิ่มข้อมูล
**** ข้อมูลไกด์
***** ค้นหา
***** เพิ่มมูลไกด์
***** สร้างไกด์ใหม่
**** ข้อมูลโรงแรม
***** ค้นหา
***** เพิ่มโรงแรม
***** สร้างโรงแรมใหม่
**** ข้อมูลพาหนะ
***** ค้นหา
***** เพิ่มพาหนะ
***** สร้างพาหนะใหม่
**** ข้อมูลลูกทัวร์
***** ค้นหา
***** เพิ่มลูกทัวร์
****** แจ้งเตือน Passport หมดอายุ
****** แจ้งเตือน วันเกิดสมาชิก
****** แจ้งเตือน หมายเหตุสมาชิก
***** สร้างลูกทัวร์ใหม่
*** จัดการข้อมูลทัวร์
**** ข้อมูลทัวร์
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลไกด์
***** เพิ่มไกด์
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลโรงแรม
***** เพิ่มโรงแรม
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลยานพาหนะ
***** เพิ่มยานพาหนะ
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลลูกทัวร์
***** เพิ่มลูกทัวร์
***** แก้ไขข้อมูล
****** แจ้งเตือน Passport หมดอายุ
****** แจ้งเตือน วันเกิดสมาชิก
****** แจ้งเตือน หมายเหตุสมาชิก
***** ลบข้อมูล
*** จัดการใบต่าง ๆ
**** จัดการใบเสนอราคา
***** สร้างใบเสนอราคา
***** แก้ไขใบเสนอราคา
***** ลบใบเสนอราคา
***** จัดการใบวางบิล
****** สร้างใบวางบิล
****** แก้ไขใบวางบิล
****** ลบใบวางบิล
**** สร้างใบแท็กติดกระเป๋า
*** คอมเมนต์
**** คอมเมนต์ทัวร์
***** ค้นหา
***** เพิ่ม
****** เลือกวันเวลา
***** แก้ไข
***** ลบ
**** คอมเมนต์ไกด์
***** ค้นหา
***** เพิ่ม
****** เลือกวันเวลา
***** แก้ไข
***** ลบ
**** คอมเมนต์โรงแรม
***** ค้นหา
***** เพิ่ม
****** เลือกวันเวลา
***** แก้ไข
***** ลบ
**** คอมเมนต์สมาชิก
***** ค้นหา
***** เพิ่ม
****** เลือกวันเวลา
***** แก้ไข
***** ลบ
**** คอมเมนต์ยานพาหนะ
***** เพิ่ม
****** เลือกวันเวลา
***** แก้ไข
***** ลบ
' *** แจ้งเตือน
' **** แจ้งเตือนข้อมูลลูกทัวร์
*** Export ข้อมูลทัวร์เป็น Excel
' ** จัดการข้อมูลบริษัทย์
' *** ข้อมูลพนักงาน
' *** จัดการข้อมูลเกี่ยวกับทัวร์
' **** ข้อมูลสมาชิกทัวร์
' **** ข้อมูลโรงแรม
' **** ข้อมูลพาหนะ
** การจัดการ
*** จัดการข้อมูลในระบบ
**** ข้อมูลพนักงาน
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
**** ข้อมูลไกด์
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
**** ข้อมูลโรงแรม
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
**** ข้อมูลพาหนะ
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
**** ข้อมูลลูกทัวร์
***** ค้นหา
***** เพิ่ม
***** ลบ
***** แก้ไข
***** คอมเมนต์
****** เพิ่ม
****** แก้ไข
****** ลบ
*** รายงานรายรับรายจ่าย
**** ค้นหา
**** แสดงแบบรายวัน
**** แสดงแบบรายรายเดือน
**** แสดงแบบรายปี
**** แสดงแบบรายเดือนแบบวัน
**** Export ข้อมูลเป็น Excel ได้
@endmindmap

' เก้า
@startmindmap
* จัดการหลังบ้านโปรแกรมทัวร์
	** ระบบสมาชิก
		*** login
		*** ข้อมูลสมาชิก
	** ระบบทัวร์
		*** จัดการทัวร์
			**** รายการทัวร์
				***** ข้อมูลลูกทัวร์
				***** ข้อมูลไกด์
				***** ข้อมูลโรงแรม
				***** ข้อมูลพาหนะ
				***** ข้อมูลลูกทัวร์
                ***** ออก tag
			**** สร้างทัวร์
				***** เพิ่มข้อมูลลูกทัวร์
				***** เพิ่มไกด์
				***** เพิ่มโรงแรม
				***** เพิ่มพาหนะ
				***** เพิ่มลูกทัวร์
			**** แก้ไขทัวร์
				***** แก้ไขทัวร์
				***** แก้ไขไกด์
				***** แก้ไขโรงแรม
				***** แก้ไขพาหนะ
				***** แก้ไขลูกทัวร์
			**** ลบทัวร์
				***** ลบทัวร์
				***** ลบไกด์
				***** ลบไขโรงแรม
				***** ลบพาหนะ
				***** ลบลูกทัวร์	
			**** สถานะทัวร์
				***** กำลังรอ
				***** พร้อม
				***** จบทริป
			**** ค้นหาทัวร์
				***** ค้นหาทัวร์
				***** ค้นหาไกด์
				***** ค้นหาโรงแรม
				***** ค้นหาพาหนะ
				***** ค้นหาลูกทัวร์
		*** จัดการคอมแมน
				**** คอมแมนทัวร์
				**** คอมแมนไกด์
				**** คอมแมนโรงแรม
				**** คอมแมนพาหนะ
				**** คอมแมนลูกทัวร์
		*** จัดการแจ้งเตือน
				**** แจ้งเตือนพาสปอร์ต
	** ระบบการเงิน
		*** จัดการใบเบิกค่าใช้จ่าย
			**** ข้อมูลใบเบิกค่าใช้จ่าย
			**** สร้างใบเบิกค่าใช้จ่าย
			**** ออกใบเคลีย
				***** ข้อมูลใบเคลีย
				***** สร้างใบเคลีย
		*** จัดการใบเสนอราคา
			**** ข้อมูลใบเสนอราคา
			**** สร้างใบเสนอราคา
			**** ใบแจ้งหนี้/ใบกำกับภาษี
				***** ข้อมูลใบแจ้งหนี้/ใบกำกับภาษี
				***** สร้างใบแจ้งหนี้/ใบกำกับภาษี
		*** จัดการใบเสร็จรับเงิน
			**** ข้อมูลใบเสร็จรับเงิน
			**** สร้างใบเสร็จรับเงิน
	** รายงาน
        *** ข้อมูลทัวร์
        *** ข้อมูลการเงิน
		*** ข้อมูลสมาชิก
@endmindmap
' เก้า 2
@startmindmap
* จัดการหลังบ้านโปรแกรมทัวร์
** ระบบสมาชิก
*** login
*** ข้อมูลสมาชิก
** จัดการทัวร์
*** ค้นหาทัวร์
*** รายการทัวร์
**** ข้อมูลทัวร์
***** แก้ไขทัวร์
***** คอมแมนทัวร์
**** ข้อมูลไกด์
***** แก้ไขไกด์
***** คอมแมนไกด์
**** ข้อมูลโรงแรม
***** แก้ไขโรงแรม
***** คอมแมนโรงแรม
**** ข้อมูลพาหนะ
***** แก้ไขพาหนะ
***** คอมแมนพาหนะ
**** ข้อมูลลูกทัวร์
***** แก้ไขลูกทัวร์
***** คอมแมนลูกทัวร์
**** สถานะทัวร์
***** กำลังรอ
***** พร้อม
***** จบทริป
**** ออก tag
**** ลบทัวร์
*** สร้างทัวร์
**** เพิ่มข้อมูลทัวร์
**** คลังข้อมูลไกด์
***** ค้นหาไกด์
***** เพิ่มไกด์
***** เลือกไกด์
**** คลังข้อมูลโรงแรม
***** ค้นหาโรงแรม
***** เพิ่มโรงแรม
***** เลือกโรงแรม
**** คลังข้อมูลพาหนะ
***** ค้นหาพาหนะ
***** เพิ่มพาหนะ
***** เลือกพาหนะ
**** คลังข้อมูลลูกทัวร์
***** ค้นหาลูกทัวร์
***** เพิ่มลูกทัว
***** เลือกลูกทัวร์
****** แจ้งเตือน 
******* แจ้งเตือน Passport หมดอายุ
******* แจ้งเตือน วันเกิดสมาชิก
******* แจ้งเตือน หมายเหตุสมาชิก
** ใบเอกสาร
*** จัดการใบเบิกค่าใช้จ่าย
**** ข้อมูลใบเบิกค่าใช้จ่าย
**** สร้างใบเบิกค่าใช้จ่าย
**** ออกใบเคลีย
***** ข้อมูลใบเคลีย
***** สร้างใบเคลีย
*** จัดการใบเสนอราคา
**** ข้อมูลใบเสนอราคา
**** สร้างใบเสนอราคา
**** ใบวางบิล/ใบแจ้งหนี้/ใบกำกับภาษี
***** จัดการใบเสร็จรับเงิน
****** ข้อมูลใบกำกับภาษี
***** จัดการใบสำคัญรับเงิน
** รายงาน
*** ข้อมูลทัวร์
*** ข้อมูลการเงิน
*** ข้อมูลสมาชิก
*** Export excel and Print

@endmindmap