@startmindmap
* Back Office

** ระบบ Login
*** Username
*** Password
** ระบบจัดการทัวร์
*** สร้างทัวร์
**** เพิ่มข้อมูล
**** ข้อมูลไกด์
***** ค้นหาไกด์
***** เลือกไกด์
***** สร้างไกด์ใหม่
**** ข้อมูลโรงแรม
***** ค้นหาโรงแรม
***** เลือกโรงแรม
***** สร้างโรงแรมใหม่
**** ข้อมูลพาหนะ
***** ค้นหาพาหนะ
***** เลือกพาหนะ
***** สร้างพาหนะใหม่
**** ข้อมูลลูกทัวร์
***** ค้นหาลูกทัวร์
***** เลือกลูกทัวร์
****** แจ้งเตือน Passport หมดอายุ
****** แจ้งเตือน วันเกิดสมาชิก
****** แจ้งเตือน หมายเหตุสมาชิก
***** สร้างลูกทัวร์ใหม่
' **** ยกเลิกการสร้างทัวร์
*** จัดการข้อมูลทัวร์
**** ข้อมูลทัวร์
***** แก้ไขข้อมูล
**** ข้อมูลไกด์
***** เลือกไกด์
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลโรงแรม
***** เลือกโรงแรม
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลยานพาหนะ
***** เลือกยานพาหนะ
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ข้อมูลลูกทัวร์
***** เลือกลูกทัวร์
****** แจ้งเตือน
******* แจ้งเตือน Passport หมดอายุ
******* แจ้งเตือน วันเกิดสมาชิก
******* แจ้งเตือน หมายเหตุสมาชิก
***** แก้ไขข้อมูล
***** ลบข้อมูล
**** ลบทัวร์
*** จัดการเอกสารภายในทัวร์
**** สร้างใบเสนอราคา
***** ใบเสนอราคา
****** แก้ไขใบเสนอราคา
****** ลบใบเสนอราคา
****** Export PDF and Print
****** สร้างใบวางบิล
******* ใบวางบิล
******** แก้ไขใบวางบิล
******** ลบใบวางบิล
******** Export PDF and Print
******** สร้างใบกำกับภาษี
********* ใบกำกับภาษี
********** แก้ไขใบกำกับภาษี
********** ลบใบกำกับภาษี
********** Export PDF and Print
********** สร้างใบเสร็จ
*********** Export PDF and Print
******** สร้างใบสำคัญรับเงิน
********* ใบสำคัญรับเงิน
********** แก้ไขใบสำคัญรับเงิน
********** ลบใบสำคัญรับเงิน
********** Export PDF and Print
**** สร้างใบสั่งงานมัคคุเทศก์
***** ใบสั่งงานมัคคุเทศก์
****** แก้ไขใบสั่งงานมัคคุเทศก์
****** ลบใบสั่งงานมัคคุเทศก์
****** Export PDF and Print
**** ใบแท็กติดกระเป๋า
***** Export PDF and Print
*** คอมเมนต์
**** คอมเมนต์ทัวร์
***** ค้นหา
***** เพิ่มคอมเมนต์ทัวร์
***** แก้ไขคอมเมนต์ทัวร์
***** ลบคอมเมนต์ทัวร์
***** เลือกวันเวลา
**** คอมเมนต์ไกด์
***** ค้นหาคอมเมนต์ไกด์
***** เพิ่มคอมเมนต์ไกด์
***** แก้ไขคอมเมนต์ไกด์
***** ลบคอมเมนต์ไกด์
***** เลือกวันเวลา
**** คอมเมนต์โรงแรม
***** ค้นหาคอมเมนต์โรงแรม
***** เพิ่มคอมเมนต์โรงแรม
***** แก้ไขคอมเมนต์โรงแรม
***** ลบคอมเมนต์โรงแรม
***** เลือกวันเวลา
**** คอมเมนต์สมาชิก
***** ค้นหาคอมเมนต์สมาชิก
***** เพิ่มคอมเมนต์สมาชิก
***** แก้ไขคอมเมนต์สมาชิก
***** ลบคอมเมนต์สมาชิก
***** เลือกวันเวลา
**** คอมเมนต์ยานพาหนะ
***** ค้นหาคอมเมนต์ยานพาหนะ
***** เพิ่มคอมเมนต์ยานพาหนะ
***** แก้ไขคอมเมนต์ยานพาหนะ
***** ลบคอมเมนต์ยานพาหนะ
***** เลือกวันเวลา
*** แจ้งเตือน
**** แจ้งเตือน Passport ลูกทัวร์หมดอายุ (ไม่มั่นใจ*)
*** Export ข้อมูลทัวร์เป็น PDF และ Print
*** สถานะทัวร์
**** สถานะกำลังรอ
**** สถานะพร้อม
**** สถานะจบทริป
** จัดการข้อมูลในระบบ
*** ข้อมูลพนักงาน
**** ค้นหาข้อมูลพนักงาน
**** เพิ่มข้อมูลพนักงาน
**** แก้ไขข้อมูลพนักงาน
**** ลบข้อมูลพนักงาน
**** ระดับพนักงาน
***** ระดับหนึ่ง
****** สิทธิ์สร้างแอคเคาท์ใหม่
****** สิทธิ์อนุมัติใบ 1 2 3 ฯ
****** สิทธิ์ในการทำสิ่งต่าง ๆ
***** ระดับสอง
***** ระดับสาม
***** ระดับสี่
***** ระดับห้า
*** ข้อมูลไกด์
**** ค้นหาข้อมูลไกด์
**** เพิ่มข้อมูลไกด์
**** แก้ไขข้อมูลไกด์
**** ลบข้อมูลไกด์
**** คอมเมนต์ข้อมูลไกด์
***** เพิ่มคอมเมนต์ข้อมูลไกด์
***** แก้ไขคอมเมนต์ข้อมูลไกด์
***** ลบคอมเมนต์ข้อมูลไกด์
*** ข้อมูลโรงแรม
**** ค้นหาข้อมูลโรงแรม
**** เพิ่มข้อมูลโรงแรม
**** แก้ไขข้อมูลโรงแรม
**** ลบข้อมูลโรงแรม
**** คอมเมนต์ข้อมูลโรงแรม
***** เพิ่มคอมเมนต์ข้อมูลโรงแรม
***** แก้ไขคอมเมนต์ข้อมูลโรงแรม
***** ลบคอมเมนต์ข้อมูลโรงแรม
*** ข้อมูลพาหนะ
**** ค้นหาข้อมูลพาหนะ
**** เพิ่มข้อมูลพาหนะ
**** แก้ไขข้อมูลพาหนะ
**** ลบข้อมูลพาหนะ
**** คอมเมนต์ข้อมูลพาหนะ
***** เพิ่มคอมเมนต์ข้อมูลพาหนะ
***** แก้ไขคอมเมนต์ข้อมูลพาหนะ
***** ลบคอมเมนต์ข้อมูลพาหนะ
*** ข้อมูลลูกทัวร์
**** ค้นหาข้อมูลลูกทัวร์
**** เพิ่มข้อมูลลูกทัวร์
**** แก้ไขข้อมูลลูกทัวร์
**** ลบข้อมูลลูกทัวร์
**** คอมเมนต์ข้อมูลลูกทัวร์
***** เพิ่มคอมเมนต์ข้อมูลลูกทัวร์
***** แก้ไขคอมเมนต์ข้อมูลลูกทัวร์
***** ลบคอมเมนต์ข้อมูลลูกทัวร์

** การเงินของบริษัท
*** สร้างใบเบิกค่าใช้จ่าย
**** ใบเบิกเงินสดย่อย
***** แก้ไขใบเบิกเงินสดย่อย
***** ลบใบเบิกเงินสดย่อย
***** Print and export to PDF
***** ออกใบเคลียร์
****** ใบเคลียร์เงินสด
******* แก้ไขใบเคลียร์เงินสด
******* ลบใบเคลียร์เงินสด
******* Print and export to PDF

** รายงานรายรับรายจ่าย
*** ค้นหารายงานรายรับรายจ่าย
*** แสดงรายงานรายรับรายจ่ายแบบรายวัน
*** แสดงรายงานรายรับรายจ่ายแบบรายรายเดือน
*** แสดงรายงานรายรับรายจ่ายแบบรายปี
*** แสดงรายงานรายรับรายจ่ายแบบรายเดือนแบบวัน
*** Export to Excel
@endmindmap